# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Interview' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  #pod 'HandyJSON'
  pod 'SnapKit'
  pod 'Alamofire'
  pod 'Toast-Swift', '~> 5.0.0'
  
  # Pods for Interview

  target 'InterviewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'InterviewUITests' do
    # Pods for testing
  end

end
